services:
  - type: web
    name: binary-options-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: telegram_bot_token
      - key: PORT
        value: 8000
